# https://mlflow.org

mlflow:
  _target_: lightning.pytorch.loggers.mlflow.MLFlowLogger
  # experiment_name: ""
  # run_name: ""
  # NOTE:
  # - if you want sqlite backend (database.db), start mlflow server:
  #     ./scripts/mlflow_server.sh
  # - then point tracking_uri to the server
  tracking_uri: http://127.0.0.1:5000
  tags: null
  # save_dir: "./mlruns"
  prefix: ""
  artifact_location: null
  # run_id: ""
