defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

# For LM we usually minimize validation loss
model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: False
  save_top_k: 0 # avoid huge full-model checkpoints; rely on adapter saving callback
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/loss"
  patience: 3
  mode: "min"

model_summary:
  max_depth: 2
